name: IOPS-FHIR-Validation-Terminology

on:
  workflow_call:
    secrets:
      ONTO_CLIENT_ID:
        required: true
      ONTO_CLIENT_SECRET:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: true

      - uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: '21'

      - name: Check out IOPS-Validation
        uses: actions/checkout@v6
        with:
          repository: ryma2fhir/Validation-github-action
          path: validation

      - name: Check out validation-service-fhir-r4
        uses: actions/checkout@v6
        with:
          repository: ryma2fhir/FHIR-JPA-Service
          ref: main
          path: validation-service-fhir-r4

      - name: Build validation service
        run: |
          cd validation-service-fhir-r4
          mvn -B -ntp package

      - name: Start Validation Service
        run: |
          cd validation-service-fhir-r4
          docker compose up -d
        env:
          CI: true
          ONTO_AUTH_URL: https://ontology.nhs.uk/authorisation/auth/realms/nhs-digital-terminology/protocol/openid-connect/token
          ONTO_SERVER_URL: https://ontology.nhs.uk/production1/fhir
          ONTO_CLIENT_ID: ${{ secrets.ONTO_CLIENT_ID }}
          ONTO_CLIENT_SECRET: ${{ secrets.ONTO_CLIENT_SECRET }}

      - name: Wait for FHIR Validator to be available
        run: |
          for i in {1..60}; do
            if curl -sSf http://localhost:8080/fhir/metadata > /dev/null; then
              echo "FHIR Validator is up!"
              exit 0
            fi
            echo "Waiting for FHIR Validator..."
            sleep 10
          done

          echo "FHIR Validator failed to start in time"
          exit 1
      
      - name: Debug directory
        run: |
          pwd
          ls -la
      
      - name: Install FHIR packages
        run: python3 validation/scripts/configure-packages.py

      - name: Upload FHIR assets + Examples
        run: python3 validation/scripts/upload-assets.py

      - name: Generate validation report
        if: always()
        run: python3 validation/scripts/generate-report.py

      - name: Stop Validation Service
        if: always()
        run: |
          cd validation-service-fhir-r4
          docker compose down
